import mdiIcons from '@iconify-json/mdi/icons.json'
import {
  createLocalFontProcessor,
} from '@unocss/preset-web-fonts/local'
import {
  defineConfig,
  presetAttributify,
  presetIcons,
  presetTypography,
  presetUno,
  presetWebFonts,
  transformerDirectives,
  transformerVariantGroup,
} from 'unocss'

export default defineConfig({
  shortcuts: [
    ['btn', 'px-4 py-1 rounded inline-block bg-main-500 text-white cursor-pointer !outline-none hover:bg-main-600 disabled:cursor-default disabled:bg-gray-600 disabled:opacity-50'],
    ['icon-btn', 'inline-block cursor-pointer select-none opacity-75 transition duration-200 ease-in-out hover:opacity-100 hover:text-main-400'],
  ],
  theme: {
    colors: {
      main: {
        50: '#fff8db',
        100: '#ffefad',
        200: '#ffe071',
        300: '#ffd152',
        400: '#f6c44a',
        500: '#e6ad2e',
        600: '#c58a1f',
        700: '#9d681b',
        800: '#704817',
        900: '#3f2d13',
        950: '#211606',
      },
      secondary: {
        50: '#f4f5f7',
        100: '#dfe2e7',
        200: '#b8bec8',
        300: '#8b95a3',
        400: '#606b78',
        500: '#3e4651',
        600: '#2b3139',
        700: '#1b2027',
        800: '#10141a',
        900: '#07090d',
        950: '#050608',
      },
    },
  },
  presets: [
    presetUno(),
    presetAttributify(),
    presetIcons({
      collections: {
        mdi: () => mdiIcons as any,
      },
      scale: 1.2,
    }),
    presetTypography(),
    presetWebFonts({
      fonts: {
        sans: 'DM Sans',
        serif: 'DM Serif Display',
        mono: 'DM Mono',
      },
      processors: createLocalFontProcessor(),
    }),
  ],
  transformers: [
    transformerDirectives(),
    transformerVariantGroup(),
  ],
  safelist: [
    ...'prose prose-sm m-auto text-left'.split(' '),
    'i-mdi-airplane',
    'i-mdi-alert',
    'i-mdi-alert-circle',
    'i-mdi-cash-multiple',
    'i-mdi-cash-refund',
    'i-mdi-car-clock',
    'i-mdi-car-hatchback',
    'i-mdi-car-info',
    'i-mdi-car-seat',
    'i-mdi-cellphone-check',
    'i-mdi-check',
    'i-mdi-check-circle',
    'i-mdi-clock-outline',
    'i-mdi-close-circle',
    'i-mdi-cog-outline',
    'i-mdi-diamond-stone',
    'i-mdi-flag-checkered',
    'i-mdi-headset',
    'i-mdi-information',
    'i-mdi-map-marker-check',
    'i-mdi-map-marker-outline',
    'i-mdi-map-marker-path',
    'i-mdi-navigation-variant',
    'i-mdi-office-building-marker',
    'i-mdi-play-circle',
    'i-mdi-plus-circle',
    'i-mdi-radar',
    'i-mdi-shield-key',
    'i-mdi-steering',
    'i-mdi-taxi',
    'i-mdi-telegram',
    'i-mdi-van-passenger',
    'i-mdi-view-grid-outline',
    'i-mdi-wallet-outline',
  ],
})
