/* eslint-disable */
/* prettier-ignore */
// oxfmt-ignore
// @ts-nocheck
// noinspection ES6UnusedImports
// Generated by vue-router. !! DO NOT MODIFY THIS FILE !!
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

import type {
  RouteRecordInfo,
  ParamValue,
  ParamValueOneOrMore,
  ParamValueZeroOrMore,
  ParamValueZeroOrOne,
} from 'vue-router'

declare module 'vue-router' {
  interface TypesConfig {
    ParamParsers: never
  }
}

declare module 'vue-router/auto-routes' {
  /**
   * Route name map generated by vue-router
   */
  export interface RouteNamedMap {
    '/[...all]': RouteRecordInfo<
      '/[...all]',
      '/:all(.*)',
      { all: ParamValue<true> },
      { all: ParamValue<false> },
      | never
    >,
    '/admin/': RouteRecordInfo<
      '/admin/',
      '/admin',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/admin/parks': RouteRecordInfo<
      '/admin/parks',
      '/admin/parks',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/admin/trips': RouteRecordInfo<
      '/admin/trips',
      '/admin/trips',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/admin/users': RouteRecordInfo<
      '/admin/users',
      '/admin/users',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/driver/': RouteRecordInfo<
      '/driver/',
      '/driver',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/driver/earnings': RouteRecordInfo<
      '/driver/earnings',
      '/driver/earnings',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/driver/login': RouteRecordInfo<
      '/driver/login',
      '/driver/login',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/driver/menu/': RouteRecordInfo<
      '/driver/menu/',
      '/driver/menu',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/driver/menu/onboarding/': RouteRecordInfo<
      '/driver/menu/onboarding/',
      '/driver/menu/onboarding',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/driver/menu/onboarding/phone': RouteRecordInfo<
      '/driver/menu/onboarding/phone',
      '/driver/menu/onboarding/phone',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/driver/menu/park-invite': RouteRecordInfo<
      '/driver/menu/park-invite',
      '/driver/menu/park-invite',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/driver/menu/support': RouteRecordInfo<
      '/driver/menu/support',
      '/driver/menu/support',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/driver/menu/vehicle': RouteRecordInfo<
      '/driver/menu/vehicle',
      '/driver/menu/vehicle',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/passenger/': RouteRecordInfo<
      '/passenger/',
      '/passenger',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/passenger/login/': RouteRecordInfo<
      '/passenger/login/',
      '/passenger/login',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/passenger/login/verify': RouteRecordInfo<
      '/passenger/login/verify',
      '/passenger/login/verify',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/passenger/menu/': RouteRecordInfo<
      '/passenger/menu/',
      '/passenger/menu',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/passenger/menu/history': RouteRecordInfo<
      '/passenger/menu/history',
      '/passenger/menu/history',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/passenger/menu/settings': RouteRecordInfo<
      '/passenger/menu/settings',
      '/passenger/menu/settings',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/passenger/menu/support': RouteRecordInfo<
      '/passenger/menu/support',
      '/passenger/menu/support',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/passenger/wallet': RouteRecordInfo<
      '/passenger/wallet',
      '/passenger/wallet',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
  }

  /**
   * Route file to route info map by vue-router.
   * Used by the \`sfc-typed-router\` Volar plugin to automatically type \`useRoute()\`.
   *
   * Each key is a file path relative to the project root with 2 properties:
   * - routes: union of route names of the possible routes when in this page (passed to useRoute<...>())
   * - views: names of nested views (can be passed to <RouterView name="...">)
   *
   * @internal
   */
  export interface _RouteFileInfoMap {
    'src/pages/[...all].vue': {
      routes:
        | '/[...all]'
      views:
        | never
    }
    'src/pages/admin/index.vue': {
      routes:
        | '/admin/'
      views:
        | never
    }
    'src/pages/admin/parks.vue': {
      routes:
        | '/admin/parks'
      views:
        | never
    }
    'src/pages/admin/trips.vue': {
      routes:
        | '/admin/trips'
      views:
        | never
    }
    'src/pages/admin/users.vue': {
      routes:
        | '/admin/users'
      views:
        | never
    }
    'src/pages/driver/index.vue': {
      routes:
        | '/driver/'
      views:
        | never
    }
    'src/pages/driver/earnings.vue': {
      routes:
        | '/driver/earnings'
      views:
        | never
    }
    'src/pages/driver/login.vue': {
      routes:
        | '/driver/login'
      views:
        | never
    }
    'src/pages/driver/menu/index.vue': {
      routes:
        | '/driver/menu/'
      views:
        | never
    }
    'src/pages/driver/menu/onboarding/index.vue': {
      routes:
        | '/driver/menu/onboarding/'
      views:
        | never
    }
    'src/pages/driver/menu/onboarding/phone.vue': {
      routes:
        | '/driver/menu/onboarding/phone'
      views:
        | never
    }
    'src/pages/driver/menu/park-invite.vue': {
      routes:
        | '/driver/menu/park-invite'
      views:
        | never
    }
    'src/pages/driver/menu/support.vue': {
      routes:
        | '/driver/menu/support'
      views:
        | never
    }
    'src/pages/driver/menu/vehicle.vue': {
      routes:
        | '/driver/menu/vehicle'
      views:
        | never
    }
    'src/pages/passenger/index.vue': {
      routes:
        | '/passenger/'
      views:
        | never
    }
    'src/pages/passenger/login/index.vue': {
      routes:
        | '/passenger/login/'
      views:
        | never
    }
    'src/pages/passenger/login/verify.vue': {
      routes:
        | '/passenger/login/verify'
      views:
        | never
    }
    'src/pages/passenger/menu/index.vue': {
      routes:
        | '/passenger/menu/'
      views:
        | never
    }
    'src/pages/passenger/menu/history.vue': {
      routes:
        | '/passenger/menu/history'
      views:
        | never
    }
    'src/pages/passenger/menu/settings.vue': {
      routes:
        | '/passenger/menu/settings'
      views:
        | never
    }
    'src/pages/passenger/menu/support.vue': {
      routes:
        | '/passenger/menu/support'
      views:
        | never
    }
    'src/pages/passenger/wallet.vue': {
      routes:
        | '/passenger/wallet'
      views:
        | never
    }
  }

  /**
   * Get a union of possible route names in a certain route component file.
   * Used by the \`sfc-typed-router\` Volar plugin to automatically type \`useRoute()\`.
   *
   * @internal
   */
  export type _RouteNamesForFilePath<FilePath extends string> =
    _RouteFileInfoMap extends Record<FilePath, infer Info>
      ? Info['routes']
      : keyof RouteNamedMap
}

export {}
