/* eslint-disable */
/* prettier-ignore */
// oxfmt-ignore
// @ts-nocheck
// noinspection ES6UnusedImports
// Generated by vue-router. !! DO NOT MODIFY THIS FILE !!
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

import type {
  RouteRecordInfo,
  ParamValue,
  ParamValueOneOrMore,
  ParamValueZeroOrMore,
  ParamValueZeroOrOne,
} from 'vue-router'

declare module 'vue-router' {
  interface TypesConfig {
    ParamParsers: never
  }
}

declare module 'vue-router/auto-routes' {
  /**
   * Route name map generated by vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<
      '/',
      '/',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/[...all]': RouteRecordInfo<
      '/[...all]',
      '/:all(.*)',
      { all: ParamValue<true> },
      { all: ParamValue<false> },
      | never
    >,
    '/admin/': RouteRecordInfo<
      '/admin/',
      '/admin',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/admin/park-chats': RouteRecordInfo<
      '/admin/park-chats',
      '/admin/park-chats',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/admin/parks': RouteRecordInfo<
      '/admin/parks',
      '/admin/parks',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/admin/trips': RouteRecordInfo<
      '/admin/trips',
      '/admin/trips',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/admin/users': RouteRecordInfo<
      '/admin/users',
      '/admin/users',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/dashboard': RouteRecordInfo<
      '/dashboard',
      '/dashboard',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/login': RouteRecordInfo<
      '/login',
      '/login',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/park/': RouteRecordInfo<
      '/park/',
      '/park',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/park/register': RouteRecordInfo<
      '/park/register',
      '/park/register',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/support/': RouteRecordInfo<
      '/support/',
      '/support',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/support/[id]': RouteRecordInfo<
      '/support/[id]',
      '/support/:id',
      { id: ParamValue<true> },
      { id: ParamValue<false> },
      | never
    >,
  }

  /**
   * Route file to route info map by vue-router.
   * Used by the \`sfc-typed-router\` Volar plugin to automatically type \`useRoute()\`.
   *
   * Each key is a file path relative to the project root with 2 properties:
   * - routes: union of route names of the possible routes when in this page (passed to useRoute<...>())
   * - views: names of nested views (can be passed to <RouterView name="...">)
   *
   * @internal
   */
  export interface _RouteFileInfoMap {
    'src/pages/index.vue': {
      routes:
        | '/'
      views:
        | never
    }
    'src/pages/[...all].vue': {
      routes:
        | '/[...all]'
      views:
        | never
    }
    'src/pages/admin/index.vue': {
      routes:
        | '/admin/'
      views:
        | never
    }
    'src/pages/admin/park-chats.vue': {
      routes:
        | '/admin/park-chats'
      views:
        | never
    }
    'src/pages/admin/parks.vue': {
      routes:
        | '/admin/parks'
      views:
        | never
    }
    'src/pages/admin/trips.vue': {
      routes:
        | '/admin/trips'
      views:
        | never
    }
    'src/pages/admin/users.vue': {
      routes:
        | '/admin/users'
      views:
        | never
    }
    'src/pages/dashboard.vue': {
      routes:
        | '/dashboard'
      views:
        | never
    }
    'src/pages/login.vue': {
      routes:
        | '/login'
      views:
        | never
    }
    'src/pages/park/index.vue': {
      routes:
        | '/park/'
      views:
        | never
    }
    'src/pages/park/register.vue': {
      routes:
        | '/park/register'
      views:
        | never
    }
    'src/pages/support/index.vue': {
      routes:
        | '/support/'
      views:
        | never
    }
    'src/pages/support/[id].vue': {
      routes:
        | '/support/[id]'
      views:
        | never
    }
  }

  /**
   * Get a union of possible route names in a certain route component file.
   * Used by the \`sfc-typed-router\` Volar plugin to automatically type \`useRoute()\`.
   *
   * @internal
   */
  export type _RouteNamesForFilePath<FilePath extends string> =
    _RouteFileInfoMap extends Record<FilePath, infer Info>
      ? Info['routes']
      : keyof RouteNamedMap
}

export {}
